### ISSUE TITLE
assignment2 dropout inline question3

### ISSUE THREAD

**Issue by euphonium1998** [bingcheng1998/CS231n-2020-spring-assignment-solution#1]
我认为这里你理解错了。我个人认为dropout是用来防止过拟合的，p值越大丢失信息越多越防止过拟合。但是题目是减少每个隐藏层的node数量，这样训练集会成功率会下降，过拟合的程度会降低，这样应该调低p才对

**Comment by bingcheng1998** [comment]
你说的没错，THX！
[这里](https://bingcheng.openmc.cn/HyperQuest/versions/ConvNet/)可以尝试dropout对模型的影响。至于dropout与hidden size之间的关系，暂时还没有提供，会在之后的版本更新，敬请期待。
