### ISSUE TITLE
some questions about knn

### ISSUE THREAD

**Issue by Eric-Zhang753** [bingcheng1998/CS231n-2020-spring-assignment-solution#4]
你好，我在运行knn代码时出现了下面附件中的状况，问题是我的代码就是他给的示例，并没有改动过，请问你遇到过这种情况吗？
![knn](https://user-images.githubusercontent.com/67717090/150669034-66bd2d80-6109-4c46-837e-4e9a120348d4.png)

**Comment by bingcheng1998** [comment]
你可以与我的代码对比一下，看看有什么区别。如果没有区别，那么可以更新使用的库的版本试试。
